[[redirects]]
  from = "http://cert.rikeijanaihito.tokyo/robots.txt"
  to = "/robots_cert.txt"
  status = 200
  force = true
[[redirects]]
  from = "http://www.rikeijanaihito.tokyo/*"
  to = "https://rikeijanaihito.tokyo/:splat"
  status = 301
  force = true